### ISSUE TITLE
staggered loading

### ISSUE THREAD

**Issue by Dieterbe** [raintank/env-load#3]
need to be gradually increase amount of orgs,
want to make load ops idempotent so that if you already have 5 and you ask for 10, it adds 5 more

**Comment by Dieterbe** [comment]
(main reason behind this is that we want to have collector backfill data which it would do for unseen jobs, without overloading itself)

**Comment by woodsaj** [comment]
i just added a commit to add a delay between creating endpoints.  It defaults to 0 (no delay).

**Comment by Dieterbe** [comment]
i like your patch, it's very simple and addresses our most urgent need (staggered loading)

i spent the last day working on a mode where it would converge any pre-existing state into the new desired state, automatically removing stuff as needed or adding new items as needed.
i've been wanting this because it would be just a bit more convenient.
this involved some refactoring and abstractions, and would have needed some more code to try to get the current user id's so they can be removed, and probably some more stuff.

it was all getting more complicated than it should have been so i decided to just revert all that work and don't implement the convergence mode.  we can readdress this later if there's a strong case for it, but right now it's just not needed enough.
